---
settings:
  name: VSC, VASA Provider, and SRA 9.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: VSC, proveedor VASA y documentos de SRA
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes.html"
  - title: Inicio rápido
    url: "/qsg.html"
  - section: deploy
  - section: manage
  - title: Avisos legales
    url: "/legal-notices.html"
