---
permalink: deploy/concept-supported-storage-system-and-applications.html 
sidebar: sidebar 
keywords: supported, storage, system, licensing, applications, virtual, appliance, vsc, vasa, provider, sra, 
summary: 'Debe conocer los requisitos básicos del sistema de almacenamiento, los requisitos de la aplicación y los requisitos de licencia antes de empezar a implementar el dispositivo virtual para Virtual Storage Console (VSC), el proveedor VASA y el adaptador de replicación de almacenamiento (SRA).' 
---
= Es compatible con el sistema de almacenamiento, las licencias y las aplicaciones para el dispositivo virtual para VSC, proveedor VASA y SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer los requisitos básicos del sistema de almacenamiento, los requisitos de la aplicación y los requisitos de licencia antes de empezar a implementar el dispositivo virtual para Virtual Storage Console (VSC), el proveedor VASA y el adaptador de replicación de almacenamiento (SRA).

El (IMT) contiene la información más reciente sobre las versiones compatibles de ONTAP, vCenter Server, hosts ESXi, aplicaciones de plugins y Site Recovery Manager (SRM).

* https://imt.netapp.com/matrix/imt.jsp?components=97563;&solution=56&isHWU&src=IMT["Herramienta de matriz de interoperabilidad: VSC 9.7.1"^]
* https://imt.netapp.com/matrix/imt.jsp?components=97564;&solution=376&isHWU&src=IMT["Herramienta de matriz de interoperabilidad: Proveedor DE VASA 9.7.1"^]
* https://imt.netapp.com/matrix/imt.jsp?components=97565;&solution=576&isHWU&src=IMT["Herramienta de matriz de interoperabilidad: SRA 9.7.1"^]


Debe habilitar la licencia de FlexClone para realizar operaciones de snapshots de máquina virtual y operaciones de clonado para almacenes de datos de VMware Virtual Volumes (vVols).

El adaptador de replicación de almacenamiento (SRA) requiere las siguientes licencias:

* Licencia de SnapMirror
+
Debe habilitar la licencia de SnapMirror para realizar operaciones de conmutación al nodo de respaldo para el SRA.

* Licencia de FlexClone
+
Debe habilitar la licencia de FlexClone para realizar operaciones de conmutación al nodo de respaldo de prueba para el SRA.



Para ver las IOPS de un almacén de datos, debe habilitar el control de I/o de almacenamiento o bien anular la selección de la casilla de comprobación Disable Storage I/o statistics Collection en la configuración de Storage I/o control. Solo puede habilitar el control de I/o de almacenamiento si tiene la licencia Enterprise Plus de VMware.

* https://kb.vmware.com/s/article/1022091["Artículo de la base de conocimientos de VMware 1022091: Solución de problemas de Storage I/o Control"^]
* https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-37CC0E44-7BC7-479C-81DC-FFFC21C1C4E3.html["Documentación de VMware vSphere: Requisitos de control de I/o de almacenamiento"^]

