---
permalink: deploy/concept-installation-workflow-for-existing-users-of-vsc.html 
sidebar: sidebar 
keywords: deployment, workflow, existing, users, vsc, vasa, provider, sra, 
summary: Las versiones 9.7 del dispositivo virtual para VSC, proveedores VASA y SRA admiten actualización directa a la versión más reciente. 
---
= Flujo de trabajo de puesta en marcha para los usuarios existentes de VSC, proveedores VASA y SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las versiones 9.7 del dispositivo virtual para VSC, proveedores VASA y SRA admiten actualización directa a la versión más reciente.

Las versiones anteriores de aplicaciones individuales como VSC, proveedores VASA y SRA usan un proceso de actualización diferente. Si tiene instalado VSC o VASA Provider o SRA en la configuración, debe realizar las siguientes operaciones:

. Ponga en marcha la versión más reciente del dispositivo virtual para VSC, proveedor VASA y SRA.
. Migre los datos de configuración existentes.
+
Los datos de configuración incluyen las credenciales del sistema de almacenamiento, así como las preferencias que se encuentran en `kaminoprefs.xml` y.. `vscPreferences.xml` archivos.



link:reference-configure-the-vsc-preferences-files.html["Configure los archivos de preferencias de VSC"^]

En muchos casos, es posible que no sea necesario migrar datos de configuración. Sin embargo, si ha personalizado anteriormente los archivos de preferencias, quizás desee revisarlos y realizar cambios similares en el dispositivo virtual recién implementado. Puede realizar una de las siguientes acciones:

* Uso https://mysupport.netapp.com/tools/index.html["Import Utility para SnapCenter y Virtual Storage Console"^] Para migrar las credenciales del sistema de almacenamiento de VSC 6.X y SRA 4.X a la nueva implementación.
* Añada los sistemas de almacenamiento al dispositivo virtual recién implementado y especifique las credenciales a medida que las añada.


Si va a actualizar desde VASA Provider 6.X, debe cancelar el registro del proveedor VASA antes de la actualización. Consulte la documentación de su versión actual para obtener más detalles.

Si también va a actualizar desde SRA 4.0 o una versión anterior:

* Si utiliza SRA 4.0P1, primero debe actualizar a SRA9.6 y solo entonces puede realizar una actualización in situ de SRA 9.6 a la última versión.
+
link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Actualice al dispositivo virtual 9.7.1 para VSC, proveedor VASA y SRA"^]

* Si utiliza SRA 2.1 o 3.0, primero debe tomar nota de los detalles de configuración del sitio existente.
+
_Guía de instalación y configuración del adaptador de replicación de almacenamiento 4.0 para ONTAP_ contiene las instrucciones detalladas en la sección "Descripción general de la actualización". Estas versiones de SRA también usan el proveedor VASA, de modo que debe anular el registro del proveedor VASA y, a continuación, poner en marcha la versión más reciente del dispositivo virtual para VSC, proveedor VASA y SRA. La versión anterior del servidor (`.ova`) se puede quitar cuando la actualización se haya completado.



Para cualquier actualización del SRA, el software del SRA (el adaptador del servidor del Site Recovery Manager, instalado por el `.msi` Archivo) debe eliminarse del servidor de Site Recovery Manager. Puede utilizar el panel de control del sistema de Windows para desinstalar el software y, a continuación, instalar el software del SRA más reciente en el servidor SRA mediante el `.msi` archivo.

Si tiene la puesta en marcha del proveedor de VASA, después de la actualización desde la configuración existente, debe configurar el tamaño de la memoria para que el dispositivo virtual sea de 12 GB con el `Edit Settings` opción. También debe modificar la reserva de memoria virtual. La máquina virtual debe estar apagada para modificar el tamaño de la memoria.

El dispositivo virtual para VSC, proveedor VASA y SRA no admite una actualización directa de cualquier versión anterior a la versión 9.7 a 9.7P2 o posterior. Primero debe actualizar la configuración existente a la versión 9.7 del dispositivo virtual para VSC, proveedor VASA y SRA antes de actualizar a cualquier versión posterior.

Si va a poner en marcha la versión más reciente del dispositivo virtual, debe ver el tema «'requisitos para poner en marcha el dispositivo virtual para VSC, proveedor VASA y SRA». El tema «'Actualizar a la versión 9.6 del dispositivo virtual para VSC, proveedores VASA y SRA'» tiene información sobre cómo realizar una actualización in situ.

*Información relacionada*

https://mysupport.netapp.com/tools/info/ECMLP2840096I.html?productID=62135&pcfContentID=ECMLP2840096["Toolchest de NetApp: Utilidad de importación para SnapCenter y Virtual Storage Console"^]

link:concept-requirements-for-deploying-the-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Requisitos para poner en marcha el dispositivo virtual para VSC, proveedor VASA y SRA"^]

link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Actualice al dispositivo virtual 9.7.1 para VSC, proveedor VASA y SRA"^]
