---
permalink: deploy/task-run-the-gos-timeout-scripts-for-windows.html 
sidebar: sidebar 
keywords: setting, timeout, values, windows, guest, operating, systems, 
summary: Las secuencias de comandos de tiempo de espera del sistema operativo invitado configuran los ajustes de tiempo de espera de I/o SCSI para sistemas operativos invitados Windows. Puede especificar un tiempo de espera de 60 segundos o un tiempo de espera de 190 segundos. Debe reiniciar el sistema operativo invitado de Windows para que la configuración surta efecto. 
---
= Configurar valores de tiempo de espera para sistemas operativos invitados de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las secuencias de comandos de tiempo de espera del sistema operativo invitado configuran los ajustes de tiempo de espera de I/o SCSI para sistemas operativos invitados Windows. Puede especificar un tiempo de espera de 60 segundos o un tiempo de espera de 190 segundos. Debe reiniciar el sistema operativo invitado de Windows para que la configuración surta efecto.

.Antes de empezar
Debe haber montado la imagen ISO que contiene la secuencia de comandos de Windows.

.Pasos
. Acceda a la consola de la máquina virtual de Windows e inicie sesión en una cuenta con privilegios de administrador.
. Si la secuencia de comandos no se inicia automáticamente, abra la unidad de CD y, a continuación, ejecute la `windows_gos_timeout.reg` guión.
+
Aparecerá el cuadro de diálogo Editor del Registro.

. Haga clic en *Sí* para continuar.
+
Se muestra el siguiente mensaje: `The keys and values contained in D:\windows_gos_timeout.reg have been successfully added to the registry.`

. Reinicie el sistema operativo invitado Windows.
. Desmonte la imagen ISO.

