---
permalink: manage/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, for, storage, systems, 
summary: Puede usar Virtual Storage Console para VMware vSphere a fin de configurar credenciales predeterminadas para un sistema de almacenamiento en el vCenter Server. 
---
= Establezca las credenciales predeterminadas para los sistemas de almacenamiento
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar Virtual Storage Console para VMware vSphere a fin de configurar credenciales predeterminadas para un sistema de almacenamiento en el vCenter Server.

.Antes de empezar
Debe haber seleccionado la instancia de vCenter Server que desea utilizar para crear credenciales predeterminadas.

.Acerca de esta tarea
Si configura credenciales predeterminadas para los sistemas de almacenamiento, Virtual Storage Console (VSC) utiliza estas credenciales para iniciar sesión en un sistema de almacenamiento que VSC acaba de detectar. Si las credenciales predeterminadas no funcionan, debe iniciar sesión manualmente en el sistema de almacenamiento. Adición de soporte para VSC y SRA de credenciales del sistema de almacenamiento en el nivel del clúster o de la SVM. Sin embargo, el proveedor de VASA solo funcionará con las credenciales en el nivel del clúster.

.Pasos
. En la página VSC *Home*, haga clic en MENU:Settings[Administrative Settings > Configure Default Credentials for Storage System].
. En el cuadro de diálogo *credenciales predeterminadas del sistema de almacenamiento*, introduzca el nombre de usuario y la contraseña del sistema de almacenamiento.
+
Las credenciales de la controladora de almacenamiento se asignan en ONTAP según el nombre de usuario y la pareja de contraseñas. Las credenciales de la controladora de almacenamiento pueden ser la cuenta de administrador o una cuenta personalizada que utilice el control de acceso basado en roles (RBAC).

+
No puede usar VSC para cambiar los roles asociados con el nombre de usuario y el par de contraseñas de la controladora de almacenamiento. Para modificar o crear un nuevo rol de usuario de ONTAP para usarlo con el dispositivo virtual para VSC, proveedor VASA y SRA, puede usar System Manager.

+
Consulte la sección «"Configuración de funciones y privilegios de usuario" en la _Virtual Storage Console, VASA Provider y Storage Replication Adapter for VMware® vSphere Deployment and Setup Guide for 9.7 Release_.

. Haga clic en *Aceptar* para guardar las credenciales predeterminadas.


.Después de terminar
Si ha actualizado las credenciales del sistema de almacenamiento porque un sistema de almacenamiento ha informado del estado "'fallo de autenticación'", haga clic en la opción *REDISCOVER ALL* disponible en la página *sistemas de almacenamiento*. Al hacerlo, VSC intenta conectarse al sistema de almacenamiento usando las nuevas credenciales.
