---
permalink: manage/task-protect-non-protected-virtual-machines.html 
sidebar: sidebar 
keywords: virtual, machines, configuring, protection, protecting, unprotected, virtual, machines, 
summary: Puede configurar la protección de las máquinas virtuales no protegidas existentes que se crearon utilizando la normativa de almacenamiento de VM con la replicación deshabilitada. Para proporcionar protección, debe cambiar la normativa de almacenamiento de equipos virtuales y asignar un grupo de replicación. 
---
= Proteja equipos virtuales sin protección
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar la protección de las máquinas virtuales no protegidas existentes que se crearon utilizando la normativa de almacenamiento de VM con la replicación deshabilitada. Para proporcionar protección, debe cambiar la normativa de almacenamiento de equipos virtuales y asignar un grupo de replicación.

.Acerca de esta tarea
Si SVM tiene tanto LIF IPv4 como IPv6, debe deshabilitar las LIF IPv6 y, más adelante, llevar a cabo flujos de trabajo de recuperación ante desastres.

.Pasos
. Haga clic en la máquina virtual necesaria y compruebe que está configurada con la política de almacenamiento de la máquina virtual predeterminada.
. Haga clic con el botón derecho en la máquina virtual seleccionada y haga clic en menu:VM Policies[Edit VM Storage Policies].
. Seleccione una política de almacenamiento de VM que tenga activada la replicación en la lista desplegable *política de almacenamiento de VM*.
. Seleccione un grupo de replicación del menú desplegable *Grupo de replicación* y, a continuación, haga clic en *Aceptar*.
+
Comprobar el resumen de la máquina virtual para confirmar que la máquina virtual está protegida.

+
[NOTE]
====
Esta versión del dispositivo virtual para VSC, proveedor VASA y SRA no admite el clonado en caliente de máquinas virtuales protegidas. Debe apagar la máquina virtual y después realizar la operación de clonado.

====

